### ISSUE TITLE
Nodrop loot.ini

### ISSUE THREAD

**Issue by towbes** [aquietone/lootnscoot#12]
I'd like to be able to set my char to loot no-drop items that are set to Keep in loot.ini, but not loot NEW no-drop items.  Is there a setting configuration to do that currently?

**Comment by aquietone** [comment]
Added a new LootNoDropNew option.
LootNoDrop controls looting no drop items which have rules defined.
LootNoDropNew controls looting no drop items which don't have an existing rule yet.
LootNoDrop needs to be on for LootNoDropNew to be checked.
